version: '2'

services:

  redis:
    image: redis
    restart: always
    command: [ redis-server, --appendonly, 'yes' ]
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    logging:
      driver: none

  dockergen:
    image: poma/docker-gen
    container_name: dockergen
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: dockergen
    volumes_from:
      - nginx
      - dockergen

  # ---------------------- ETH ----------------------- #

  eth-server:
    build: .
    image: local/portalgate/zk-relayer/4.14
    profiles: [ 'eth' ]
    restart: always
    command: server
    # env_file: .env.eth
    environment:
      NET_ID: 1
      REDIS_URL: redis://redis/0
      nginx_proxy_read_timeout: 600
    depends_on: [ redis ]

  eth-healthWatcher:
    image: local/portalgate/zk-relayer/4.14
    profiles: [ 'eth' ]
    restart: always
    command: healthWatcher
    # env_file: .env.eth
    environment:
      NET_ID: 1
      REDIS_URL: redis://redis/0
    depends_on: [ redis, eth-server ]

  eth-worker1:
    image: local/portalgate/zk-relayer/4.14
    profiles: [ 'eth' ]
    restart: always
    command: worker
    # env_file: .env.eth
    environment:
      NET_ID: 1
      REDIS_URL: redis://redis/0
    depends_on: [ redis, eth-server ]

  # ---------------------- GETH ---------------------- #

  geth-server:
    build: .
    image: local/portalgate/zk-relayer/4.14
    profiles: [ 'geth' ]
    restart: always
    command: server
    env_file: .env.geth
    environment:
      NET_ID: 5
      REDIS_URL: redis://redis/7
      nginx_proxy_read_timeout: 600
    depends_on: [ redis ]

  geth-healthWatcher:
    image: local/portalgate/zk-relayer/4.14
    profiles: [ 'geth' ]
    restart: always
    command: healthWatcher
    env_file: .env.geth
    environment:
      NET_ID: 5
      REDIS_URL: redis://redis/7
    depends_on: [ redis, geth-server ]

  geth-worker1:
    image: local/portalgate/zk-relayer/4.14
    profiles: [ 'geth' ]
    restart: always
    command: worker
    env_file: .env.geth
    environment:
      NET_ID: 5
      REDIS_URL: redis://redis/7
    depends_on: [ redis, geth-server ]
  # -------------------------------------------------- #

volumes:
  conf:
  vhost:
  html:
  certs:
  redis:


